* emacs

very nice guide: https://00stack.in/nixos-ressources/pbp-nixos

emacs color :notes
https://darksair.org/blog/p/2018/uhd-is-future/
https://en.wikipedia.org/wiki/CIECAM02
http://www.brucelindbloom.com/index.html?WorkingSpaceInfo.html

https://en.wikipedia.org/wiki/SRGB

todo: LCH hue is in radians? or degrees?
    hue is in degrees, might be negative
    what does a negative hue mean? tried a LCH transform to ensure positive, got differing results
;; (if (> 0 H) (* -1 H) H)
want: helpers for working with hue in degrees -> whatever color.el LCH expects
    maybe: -1 is -180 and 1 is 180? doesn't appear to be... hue is weird.

todo: persist the variable that holds visited directories on occasion

improve your pager game maybe -- better buffer name? no file association?

need to get an org solution with agenda/reminders/carryover

idea: experiment with a keybind for saving layout and then restoring it later - maybe you could even name layouts

https://github.com/akermu/emacs-libvterm/issues/115#issuecomment-521303725

try out dired copy paste operations/do they persist when you aggressively cull the dired buffers like you do
maybe add a dired focus hook to refresh the display, irritating when the reference is old

idea: unpop shells not in the current frame on shell-pop
    it's kind of annoying to see the same text when you have shell-1 open in different windows at the same time

idea: make a sql query backend for qutebrowser to use here: https://github.com/cireu/counsel-ffdata

maybe checkout LSP mode as well

neat proced htop-like graph
https://gitlab.com/RobertCochran/neato-graph-bar
proced mode
needs proced-update

try to get some ideas from this https://medium.com/breathe-publication/understanding-vims-jump-list-7e1bfc72cdf0
idea: org links to xref trail
idea: jump to pop shell show last command running process

** plugins
*** org
**** https://github.com/sergeyklay/bnf-mode
**** https://github.com/dengste/org-caldav
**** https://github.com/justbur/emacs-vdiff                            :doom:
**** https://github.com/benma/visual-regexp-steroids.el
    maybe come back to this -- I don't like the live editing in the minibuffer because you then can't get the query you made very easily. Maybe we can come back and use like a standalone buffer to highlight in a test output or something

    (I just like regextesters interface on the inter dot net I guess)
*** other
**** expand region
**** https://github.com/kostafey/ejc-sql
**** https://github.com/hlolli/csound-mode
**** https://github.com/Fuco1/dired-hacks
**** https://github.com/ilya-babanov/emacs-bpr
**** https://github.com/clojure-emacs/clj-refactor.el
**** large file mode: https://github.com/m00natic/vlfi                 :doom:
**** https://github.com/magit/with-editor
**** https://github.com/justbur/emacs-vdiff                            :doom:
**** ledger-mode                                                       :doom:
checkout: https://github.com/atheriel/evil-ledger -- but you will have
to change your cx command binding for exchange (transactions use x in
ledger)

**** https://github.com/NicolasPetton/Indium
**** https://github.com/tumashu/ivy-posframe
make this HUGE
**** https://github.com/abo-abo/auto-yasnippet
**** https://github.com/kaz-yos/eval-in-repl/tree/fea05a5b81d74ac53cb2a83aa83a73d9526bcc42
**** https://github.com/skangas/mentor
**** https://github.com/ppareit/graphviz-dot-mode
a nice dot reference: http://tonyballantyne.com/graphs.html
maybe add both of these to http://notes.neeasade.net/tldr-org-mode--graphviz.html
*** TODO https://github.com/purcell/envrc
** ideas
*** org
**** checkout languagetool https://www.reddit.com/r/emacs/comments/fxs92h/comment/fmxqhpb
**** https://www.reddit.com/r/emacs/comments/8nvnlu/extending_orgmode/
**** https://github.com/integral-dw/org-superstar-mode
give this a go
**** http://emacs.cafe/emacs/orgmode/gtd/2017/06/30/orgmode-gtd.html
**** https://emacs.stackexchange.com/questions/477/how-do-i-automatically-save-org-mode-buffers
**** http://emacs.cafe/emacs/orgmode/gtd/2017/06/30/orgmode-gtd.html

**** into org agendas
**** https://github.com/TeMPOraL/conffiles/blob/master/emacs26/.emacs.d/elisp/init-org-mode.el
**** https://github.com/Kungsgeten/org-brain#other-useful-packages
*** other
**** https://www.reddit.com/r/emacs/comments/bg1018/rediscovering_vanilla_emacs_text_editing/eliw0f1/

**** https://stackoverflow.com/questions/32822036/how-to-kill-all-buffers-with-buffer-file-in-a-certain-location
**** http://endlessparentheses.com/leave-the-cursor-at-start-of-match-after-isearch.html
**** https://www.reddit.com/r/emacs/comments/9ucpg1/for_people_using_the_default_emacs_keybindings/e939fnw/

**** review: https://sanctum.geek.nz/arabesque/advanced-vim-registers/
**** latex workflow https://github.com/The-Compiler/dotfiles/blob/master/spacemacs#L497

**** shell-mode check running processes
https://stackoverflow.com/questions/8291899/is-there-a-direct-elisp-way-to-check-if-a-process-is-running-in-an-emacs-term-bu
can fix hanging auto CD on long running processes
**** shell-pop cd tramp smart
potentially use dired logic as reference -- find some shell-mode present on the $host without a running process or create one
**** http://kitchingroup.cheme.cmu.edu/blog/category/emacs/
**** https://www.reddit.com/r/emacs/comments/8of6tx/tip_how_to_be_a_beast_with_hydra/
**** https://www.reddit.com/r/emacs/comments/8ekz0u/how_to_pastethencopy/
maybe just treat some mark as implicit paste target for a keybind
add a hook for on evil yank and then remove it on yank?
**** https://stackoverflow.com/questions/32822036/how-to-kill-all-buffers-with-buffer-file-in-a-certain-location
**** steal latex setup from https://github.com/rememberYou/.emacs.d
****  idea: jump to input prompt area keybind
- deadgrep
- comint prompt area
- irc message prompt?

in deadgrep mode, a keybind to change the search, and filetype
(jumping back to the top is getting annoying) also for comint
mode/shell, irc... (think I will use nf)

This hasn't happened because it's not _super_ inconvienent to gg or G to where I need to go

**** https://stackoverflow.com/questions/32822036/how-to-kill-all-buffers-with-buffer-file-in-a-certain-location
** maybe/not really interested
*** https://github.com/wolray/symbol-overlay
*** https://github.com/mpdel/mpdel
you're currently pretty satisfied with mpc and your music script
The one reason this is still in the list is maybe for the playlist/mpd view could be cool.

** emacs conf 2019
look into debug adapter protocol

** pinebook pro emacs issues
failed to get:  ts, better-jumper, flyspell-correct-avy-menu
failed with error: org-pomodoro

** pinebook pro dotfiles issues
need to support more fallback terms -- konsole is what shippped with it -- maybe scrape a list from arch wiki

battery location:

#+begin_src diff
+BATC=/sys/class/power_supply/cw2015-battery/capacity
+BATS=/sys/class/power_supply/cw2015-battery/status
#+end_src

xbright script:
#+begin_src diff
-echo xrandr --output LVDS-1 --brightness 0$(echo "$current / 100" | bc -l | cut -c -3)
-xrandr --output LVDS-1 --brightness 0$(echo "$current / 100" | bc -l | cut -c -3)
+# echo xrandr --output LVDS-1 --brightness 0$(echo "$current / 100" | bc -l | cut -c -3)
+# xrandr --output eDP-1 --brightness 0$(echo "$current / 100" | bc -l | cut -c -3)
+max=$(cat /sys/class/backlight/edp-backlight/max_brightness)
+result=$(echo "$current / 100 * $max" | bc -l | awk -F. '{print $1}')
+echo "$result" | sudo tee /sys/class/backlight/edp-backlight/brightness
+echo "$result / $max"
#+end_src
