#!/bin/sh

target=$(mktemp)

(
    while IFS= read -r line; do
    printf '%s\n' "$line"
    done <&0
) > "$target"


window_height=$(elisp '(- (window-total-height) 2)')
if [ $? -ne 0 ]; then
    # we can't reach emacs, use cat.
    cat "$target"
else
    if [ $(wc -l < "$target") -lt "$window_height" ]; then
	cat "$target"
    else
	first_line=$(head -n 1 "$target")

	if [[ $first_line = diff* ]]; then
	    mode=diff-mode
	else
	    mode=${1:-text-mode}
	fi

	elisp "(ns/find-or-open \"${target}\") (${mode}) (Man-cleanup-manpage)"
    fi
fi

rm "$target"
