#!/bin/sh
target="$(mktemp)"

(
    while IFS= read -r line; do
    printf '%s\n' "$line"
    done <&0
) > "$target"

# arbitrary
if [ $(wc -l < "$target") -lt 25 ]; then
    cat "$target"
else
    mode="${1:-text-mode}"
    elisp "(ns/find-or-open \"${target}\") (${mode})"
fi

rm "$target"
