#!/bin/bash

candidates=""

if [ -p /dev/stdin ]; then
    candidates="$(cat -)"
else
    candidates="$(rg --files "$@")"
fi

# todo: make this an actual temp file-- this was the fastest cross platform way to keep cleanup
file="$(elisp -r '(~ "fzftemp")')"

echo "$candidates" > "$file"

lisp='(ivy-read "" (s-split "\n" (get-string-from-file "'"$file"'")) :action (lambda(option) option))'

if result="$(elisp "${lisp}")"
then
    echo "$result" | sed -e 's/^"//' -e 's/"$//'
else
    exit 1
fi
